title: Think Python, 2nd
description: >-
  This textbook is adopted from https://greenteapress.com/wp/think-python-2e/.
footer: A project by the Language and Educational Analytics Research (Lear)Lab
favicon: /images/avatars/favicon.png
